# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_1/pwm_1.xci
# IP: The module: 'pwm_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_1/src/Basys3_Master-1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_1/pwm_1.xci
# IP: The module: 'pwm_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_1/src/Basys3_Master-1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
