# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.cache/wt [current_project]
set_property parent.project_path C:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths c:/XilinxWorking/Lab5/2_1_PWM_IP/ip_repo [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet C:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.runs/pwm_1_synth_1/pwm_1.dcp
set_property used_in_implementation false [get_files C:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.runs/pwm_1_synth_1/pwm_1.dcp]
read_verilog -library xil_defaultlib C:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/imports/Downloads/dim_leds.v
read_xdc C:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.srcs/constrs_1/imports/Lab3/Basys3_Master-1.xdc
set_property used_in_implementation false [get_files C:/XilinxWorking/Lab5/2_1_PWM_test/2_1_PWM_test.srcs/constrs_1/imports/Lab3/Basys3_Master-1.xdc]

synth_design -top dim_leds -part xc7a35tcpg236-1
write_checkpoint -noxdef dim_leds.dcp
catch { report_utilization -file dim_leds_utilization_synth.rpt -pb dim_leds_utilization_synth.pb }
